import D from D.jpg
import Dm from Dm.jpg
import C from C.png
import Cs from Cs.png
import Csm from Csm.png
import Cm from Cm.png
import B from B.png
import Bm from Bm.png
import A from A.png
import Am from Am.png
import Abm from Abm.png
import G from G.png
import Gm from Gm.png
import E from E.png
import Em from Em.png
import F from F.png
import Fm from Fm.png
import Fs from Fs.png
import Fsm from Fsm.png
